# Generated by Django 4.2.3 on 2023-07-26 01:27

import django.core.validators
from django.db import migrations, models
import school.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.IntegerField(choices=[(1, 'school')], default=1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[가-힣]{2,25}$', 'Theschool name must be written in 2-55 Korean characters', 'school_name_invalid')])),
                ('logo_image', models.ImageField(blank=True, upload_to=school.models.school_logo_directory_path)),
            ],
        ),
    ]
