spring:
    # MySQL ?? ??
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/atibo?characterEncoding=utf8
        url: jdbc:mysql://mysql-container:3306/atibo
#        username: root
#        password: 1q2w3e4r!

    # JPA ??
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            show_sql: true # ???? ?? ?? ??
            format_sql: true # ???? ???? ??? ???? ?? ???
            naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStanderImpl
    # 개발용(Postman 요청)
    security:
        user:
            name: user
            password: 1234

    # 임의의 긴 암호 문자열
    jwt:
        secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

# TODO: test 해보고 삭제해도 될듯( csrf 설정 )
    mustache:
        servlet:
            expose-request-attributes: true

    #   메일 발송
    mail:
        host: smtp.gmail.com
        port: 587
        username: "atibo5268@gmail.com"
        password: "dgktrgaygqnvmuqr"
        properties:
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true

    #    subject:
    #        user:
    #            password-reset: "[ATIBO] new password"

logging:
    level:
        org.hibernate.SQL: debug # logger에 출력하려면
        org.hibernate.type.descriptor.sql: TRACE
#   세션 소멸시간
server:
    servlet:
        session:
            timeout: 90m
