spring:
    # MySQL
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${DB_IP}:${DB_PORT}/${DB_NAME}
        username: ${DB_USER}
        password: ${DB_PASSWORD}

    # JPA ??
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            show_sql: true
            format_sql: true
            naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStanderImpl

    # 임의의 긴 암호 문자열
    jwt:
        secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

    # csrf 설정
    mustache:
        servlet:
            expose-request-attributes: true

    #   메일 발송
    mail:
        host: ${EMAIL_HOST}
        port: ${EMAIL_PORT}
        username: ${EMAIL_HOST_USER}
        password: ${EMAIL_HOST_PASSWORD}
        properties:
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true

logging:
    level:
        org.hibernate.SQL: debug
        org.hibernate.type.descriptor.sql: TRACE
#   세션 소멸시간
server:
    servlet:
        session:
            timeout: 90m
