# Generated by Django 4.2.3 on 2023-07-26 01:32

import atibo.fields
import django.core.validators
from django.db import migrations, models
import school.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='logo_image',
            field=models.ImageField(null=True, upload_to=school.models.school_logo_directory_path),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2, 'The school name length must be greater than 0')]),
        ),
    ]
