"""
Django settings for atibo project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
import environ

from pathlib import Path
from datetime import timedelta

# Default Setting for 'django-environ' 
env = environ.Env(
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent

# Add '/apps' to the Python Interpretor's module path

sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Take environment variables from .env file

environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = env('DEBUG')

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Activating Models
    # https://docs.djangoproject.com/en/4.2/intro/tutorial02/#activating-models
    'accounts.apps.AccountsConfig',
    'students.apps.StudentsConfig',
    'gym.apps.GymConfig',
    'school.apps.SchoolConfig',

    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'drf_spectacular_sidecar',  # required for Django collectstatic discovery. UI contained drf_spectacular

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# rest_framework setting
# Effective only for API views created with Django Rest Framework

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',    # simple JWT authentication
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '50/minute'
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'atibo.exceptions.default_exception_handler',
}

# rest_framework_simplejwt setting

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=20),
    "REFRESH_TOKEN_LIFETIME": timedelta(hours=8),
    "ALGORITHM": "HS384",
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
}

# drf_spectacular setting

SPECTACULAR_SETTINGS = {
    'TITLE': 'ATIBO API',
    'DESCRIPTION': 'The smart kiosk program for managing ATtendance and InBOdy',
    'VERSION': '2.0.0',
    'SERVE_INCLUDE_SCHEMA': False,

    'SWAGGER_UI_DIST': 'SIDECAR',  # shorthand to use the sidecar instead
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', # Activate Translation. After SessionMideware & Befroe CommonMidware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'atibo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'atibo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# https://docs.djangoproject.com/en/4.2/ref/databases/#connecting-to-the-database

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS': {
            'read_default_file': os.path.join(BASE_DIR, 'atibo/mysql.cnf'),
            'init_command': 'SET default_storage_engine=INNODB' 
        },
    }
}

# Tying transactions to HTTP requests.
# https://docs.djangoproject.com/en/4.2/topics/db/transactions/#tying-transactions-to-http-requests
'''
ATOMIC_REQUESTS = True

1. Not working when Integrity Error is handled by Exption Handler or try statement
   https://github.com/encode/django-rest-framework/issues/2034
2. Tying every requests is inefficient
   https://docs.djangoproject.com/en/4.2/topics/db/transactions/#tying-transactions-to-http-requests

Therefore, Manually tie each fucntion with `@transaction.atomic` decorator
'''

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        "OPTIONS": { "min_length": 8 },
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'atibo.validators.NumberValidator',
    },
    {
        'NAME': 'atibo.validators.SpecialCharValidator',
    },
]

# Change the Password Hasher from the default 'PBKDF2PasswordHasher'
# https://docs.djangoproject.com/en/4.2/topics/auth/passwords/#how-django-stores-passwords

PASSWORD_HASHERS = [env.str('PRIMARY_PASSWORD_HASHER', default='django.contrib.auth.hashers.PBKDF2PasswordHasher')]

AUTH_USER_MODEL = 'accounts.User'

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Setting
# https://docs.djangoproject.com/en/4.2/topics/email/#obtaining-an-instance-of-an-email-backend

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = env('EMAIL_HOST')

EMAIL_PORT = env('EMAIL_PORT')

EMAIL_HOST_USER = env('EMAIL_HOST_USER')

EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')

EMAIL_USE_TLS = True

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
