# Generated by Django 4.2.3 on 2023-08-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_student_unique_grade_room_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inbody',
            name='test_per_day',
        ),
        migrations.AddField(
            model_name='inbody',
            name='is_constraint_activated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='inbody',
            constraint=models.UniqueConstraint(fields=('student', 'test_date', 'is_constraint_activated'), name='unique_student_test_date_activated_constraint'),
        ),
    ]
