# Generated by Django 4.2.3 on 2023-08-06 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='comment',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10, '소개글은 10자 이상으로 작성해주세요')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[가-힣]{2,5}$', '이름은 2~5자의 한글로 작성해주세요', 'name_invalid')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(editable=False, max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^(?=.*[A-Za-z])[A-Za-z\\d]{5,20}$', '아이디는 영어와 숫자를 조합하여 5~20 자로 작성해주세요', 'username_invalid')]),
        ),
    ]
