# Generated by Django 4.2.3 on 2023-08-07 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_comment_alter_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^(?=.*[A-Za-z])[A-Za-z\\d]{5,20}$', '아이디는 영어와 숫자를 조합하여 5~20 자로 작성해주세요', 'username_invalid')]),
        ),
    ]
