# Generated by Django 4.2.3 on 2023-07-27 04:33

import django.core.validators
from django.db import migrations, models
import gym.models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_alter_equipment_description_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2, 'The name length must be longer than 2')]),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to=gym.models.gym_equipment_directory_path),
        ),
    ]
