# Generated by Django 4.2.3 on 2023-08-06 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_remove_image_image_equipment_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2, '이름은 2글자 이상으로 작성해주세요')]),
        ),
    ]
