# Generated by Django 4.2.3 on 2023-07-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_inbody_attendance_attendance_student_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbody',
            old_name='bobdy_mass_index',
            new_name='body_mass_index',
        ),
    ]
