# Generated by Django 4.2.3 on 2023-07-26 01:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_bobdy_mass_index_inbody_body_mass_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inbody',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[가-힣]{2,5}$', 'The name must be written in 2-5 Korean characters', 'name_invalid')]),
        ),
    ]
