# Generated by Django 4.2.3 on 2023-07-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_attendance_id_alter_inbody_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_attended',
            field=models.DateTimeField(),
        ),
    ]
