# Generated by Django 4.2.3 on 2023-08-06 08:56

import atibo.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_attendance_date_attended'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='unique_grade_room_number',
        ),
        migrations.AddField(
            model_name='student',
            name='is_constraint_activated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inbody',
            name='age',
            field=atibo.fields.TinyIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, '나이는 0보다 커야 합니다'), django.core.validators.MaxValueValidator(127, '나이는 128보다 작아야 합니다')]),
        ),
        migrations.AlterField(
            model_name='inbody',
            name='score',
            field=atibo.fields.TinyIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, '인바디 점수는 0보다 커야 합니다'), django.core.validators.MaxValueValidator(100, '인바디 점수는 100이하여야 합니다')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=atibo.fields.TinyIntegerField(validators=[django.core.validators.MinValueValidator(1, '학년은 0보다 커야 합니다'), django.core.validators.MaxValueValidator(9, '학년은 10보다 작아야 합니다')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[가-힣]{2,5}$', '이름은 2~5자의 한글로 작성해주세요', 'name_invalid')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='number',
            field=atibo.fields.TinyIntegerField(validators=[django.core.validators.MinValueValidator(1, '번호는 0보다 커야 합니다'), django.core.validators.MaxValueValidator(100, '번호는 100 이하여야 합니다')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='0000', max_length=4, validators=[django.core.validators.MinLengthValidator(4, '비밀번호의 길이는 4자여야 합니다'), django.core.validators.RegexValidator('^\\d{4}$', '비밀번호는 숫자로만 이뤄져야 합니다', 'student_password_invalid')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='room',
            field=atibo.fields.TinyIntegerField(validators=[django.core.validators.MinValueValidator(1, '반은 0보다 커야 합니다'), django.core.validators.MaxValueValidator(99, '반은 100보다 작아야 합니다')]),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('grade', 'room', 'number', 'is_constraint_activated'), name='unique_grade_room_number_activated'),
        ),
    ]
